[package]
name = "return-ok"
version = "0.0.0"
edition = "2024"
categories = ["rust-patterns"]
description = "Macros for dealing with Options and Results where you shouldn't"
keywords = ["macro", "option", "result"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/DragonFoxCollective/return-ok"
exclude = [".vscode/", "Cargo.lock"]

[dependencies]
